stage('Update Kubernetes Manifest') {
    steps {
        script {
            sh """
            # On est déjà dans le dépôt au début du pipeline
            # (le checkout du début a cloné ici)

            git config user.email "ci@jenkins.com"
            git config user.name "Jenkins CI"

            sed -i "s|image:.*|image: $DOCKER_IMAGE:$TAG|" k8s/deployment.yaml

            git add k8s/deployment.yaml
            git commit -m "Update image to version $TAG" || echo "No changes"
            git push origin $GIT_BRANCH
            """
        }
    }
}
